Require Import bluerock.auto.invariants.
Require Import bluerock.auto.cpp.proof.
Require Import monad.proofs.misc.
Require Import bluerock.auto.cpp.tactics4.
Require Import monad.tutorials.demo2.
Require Import monad.tutorials.demomisc.
From AAC_tactics Require Import AAC.
From AAC_tactics Require Import Instances.
Import Instances.Z.
Import stdpp.list.
Import stdpp.decidable.
Import cQp_compat.
Open Scope cQp_scope.
Open Scope Z_scope.
Import linearity.
Import Verbose.
Ltac slauto := misc.slauto1.
Disable Notation take.
Disable Notation drop.
Disable Notation "`div`" (all).
Disable Notation intR.
Disable Notation uintR.
Import linearity.
Disable Notation atomic_name'.
Disable Notation atomic_name.
Open Scope pstring_scope.
Set Printing FullyQualifiedNames.
Require Import monad.asts.block_state_cpp. (* this defines module: translation_unit, the  AST of block_state.cpp (and all its transitive includes). block_state_cpp.v is autogenerated by cpp2v *)


(*
In the current Coq context, I have `block_state_cpp.module:translation_unit` which is a translation of the AST of block_state.cpp (and its includes, recursively) to Coq.
Write a gallina function `find_struct` that takes a `translation_unit` and an argumement `nm: name` and returns an `option _` which is a definition of the struct whose fully qualified name is `name`. Chose an appropriate type for the placeholder `_`.

+++ QUERIES
Print translation_unit.
Print name.
*)
Definition find_struct
  (tu : bluerock.lang.cpp.syntax.translation_unit.translation_unit)
  (nm : bluerock.lang.cpp.syntax.core.name)
  : option bluerock.lang.cpp.syntax.decl.Struct :=
  match bluerock.lang.cpp.syntax.namemap.internal.NameMap.find
          (elt := bluerock.lang.cpp.syntax.translation_unit.GlobDecl)
          nm (bluerock.lang.cpp.syntax.translation_unit.types tu) with
  | Some (bluerock.lang.cpp.syntax.translation_unit.Gstruct s) => Some s
  | _ => None
  end.






