// DO NOT EDIT THIS FILE! If you need changes, change the code generator
// instead. This file was generated by running the following command:
//
//    ../../python/cg-events c -p .

#include <stddef.h>

#include <monad/event/event.h>
#include <monad/event/event_metadata.h>

#ifdef __cplusplus
extern "C"
{
#endif

// clang-format off

struct monad_event_metadata const g_monad_event_metadata[] = {

    [MONAD_EVENT_NONE] =
        {.type = MONAD_EVENT_NONE,
         .c_name = "NONE",
         .description = "reserved code so that 0 remains invalid"},

    [MONAD_EVENT_RING_INIT] =
        {.type = MONAD_EVENT_RING_INIT,
         .c_name = "RING_INIT",
         .description = "Posted when a recorder ring is enabled after being reset"},

    [MONAD_EVENT_THREAD_CREATE] =
        {.type = MONAD_EVENT_THREAD_CREATE,
         .c_name = "THREAD_CREATE",
         .description = "Sent when a new thread starts recording data"},

    [MONAD_EVENT_THREAD_EXIT] =
        {.type = MONAD_EVENT_THREAD_EXIT,
         .c_name = "THREAD_EXIT",
         .description = "Sent immediately before a thread exits"},

    [MONAD_EVENT_HEARTBEAT] =
        {.type = MONAD_EVENT_HEARTBEAT,
         .c_name = "HEARTBEAT",
         .description = "Periodic heartbeat emitted by the event server"},

    [MONAD_EVENT_TEST_COUNTER] =
        {.type = MONAD_EVENT_TEST_COUNTER,
         .c_name = "TEST_COUNTER",
         .description = "A special event emitted only by the test suite"},

};

size_t const g_monad_event_metadata_size = 5;

uint8_t const g_monad_event_metadata_hash[32] = {
    0x10, 0xd2, 0x65, 0x13, 0x5e, 0x07, 0xad, 0xe9,
    0xff, 0x7b, 0x34, 0xc4, 0xd4, 0xf4, 0x73, 0x57,
    0x6b, 0x0f, 0x95, 0x34, 0x09, 0x04, 0xc5, 0x52,
    0xba, 0x86, 0xcb, 0x5c, 0x82, 0x29, 0x89, 0x2b,
};

#ifdef __cplusplus
} // extern "C"
#endif
