#pragma once

// DO NOT EDIT THIS FILE! If you need changes, change the code generator
// instead. This file was generated by running the following command:
//
//    ../../python/cg-events c -p .

/**
 * @file
 *
 * Core definitions of event enumeration types and event payload structures
 */

#include <stdint.h>

// clang-format off
#ifdef __cplusplus

#include <string.h>

struct evmc_address;
struct evmc_bytes32;

extern "C"
{
#endif

/// Each type of event is assigned a unique value in this enumeration
enum monad_event_type : uint16_t
{
    MONAD_EVENT_NONE,
    MONAD_EVENT_RING_INIT,
    MONAD_EVENT_THREAD_CREATE,
    MONAD_EVENT_THREAD_EXIT,
    MONAD_EVENT_HEARTBEAT,
    MONAD_EVENT_TEST_COUNTER,
};

/// Event payload for MONAD_EVENT_THREAD_CREATE
struct monad_event_thread_info
{
    uint64_t epoch_nanos;
    uint64_t process_id;
    uint64_t thread_id;
    uint8_t source_id;
    char thread_name[31];
};

/// Event payload for MONAD_EVENT_TEST_COUNTER
struct monad_event_test_counter
{
    uint8_t writer_id;
    uint64_t counter;
};

#ifdef __cplusplus
} // extern "C"

// clang-format on
#endif
