// DO NOT EDIT THIS FILE! If you need changes, change the code generator
// instead. This file was generated by running the following command:
//
//    ../../python/cg-events c -p .

#include <stddef.h>

#include <monad/event/event.h>
#include <monad/event/event_metadata.h>
#include <monad/event/event_types.h>

#ifdef __cplusplus
extern "C"
{
#endif

// clang-format off

struct monad_event_metadata const g_monad_event_metadata[] = {

    [MONAD_EVENT_NONE] =
        {.type = MONAD_EVENT_NONE,
         .c_name = "NONE",
         .description = "reserved code so that 0 remains invalid"},

    [MONAD_EVENT_RING_INIT] =
        {.type = MONAD_EVENT_RING_INIT,
         .c_name = "RING_INIT",
         .description = "Posted when a recorder ring is enabled after being reset"},

    [MONAD_EVENT_THREAD_CREATE] =
        {.type = MONAD_EVENT_THREAD_CREATE,
         .c_name = "THREAD_CREATE",
         .description = "Sent when a new thread starts recording data"},

    [MONAD_EVENT_THREAD_EXIT] =
        {.type = MONAD_EVENT_THREAD_EXIT,
         .c_name = "THREAD_EXIT",
         .description = "Sent immediately before a thread exits"},

    [MONAD_EVENT_TEST_COUNTER] =
        {.type = MONAD_EVENT_TEST_COUNTER,
         .c_name = "TEST_COUNTER",
         .description = "A special event emitted only by the test suite"},

    [MONAD_EVENT_BLOCK_START] =
        {.type = MONAD_EVENT_BLOCK_START,
         .c_name = "BLOCK_START",
         .description = "Started execution of a proposed block"},

    [MONAD_EVENT_BLOCK_END] =
        {.type = MONAD_EVENT_BLOCK_END,
         .c_name = "BLOCK_END",
         .description = "Proposed block with this flow ID has completed execution (may not be finalized)"},

    [MONAD_EVENT_BLOCK_FINALIZE] =
        {.type = MONAD_EVENT_BLOCK_FINALIZE,
         .c_name = "BLOCK_FINALIZE",
         .description = "Block is committed on the canonical blockchain"},

    [MONAD_EVENT_BLOCK_REJECT] =
        {.type = MONAD_EVENT_BLOCK_REJECT,
         .c_name = "BLOCK_REJECT",
         .description = "Block failed validation and was rejected"},

    [MONAD_EVENT_BLOCK_EXEC_ERROR] =
        {.type = MONAD_EVENT_BLOCK_EXEC_ERROR,
         .c_name = "BLOCK_EXEC_ERROR",
         .description = "Block execution failed due to error in the EVM, not due to it being invalid"},

    [MONAD_EVENT_TXN_START] =
        {.type = MONAD_EVENT_TXN_START,
         .c_name = "TXN_START",
         .description = "Started execution of new transaction"},

    [MONAD_EVENT_TXN_REJECT] =
        {.type = MONAD_EVENT_TXN_REJECT,
         .c_name = "TXN_REJECT",
         .description = "Transaction failed validation and was rejected - no receipt, not in block"},

    [MONAD_EVENT_TXN_EXEC_ERROR] =
        {.type = MONAD_EVENT_TXN_EXEC_ERROR,
         .c_name = "TXN_EXEC_ERROR",
         .description = "Transaction execution failed due to error in the EVM, not due to it being invalid"},

    [MONAD_EVENT_TXN_LOG] =
        {.type = MONAD_EVENT_TXN_LOG,
         .c_name = "TXN_LOG",
         .description = "Transaction emitted a log during speculative execution"},

    [MONAD_EVENT_TXN_RECEIPT] =
        {.type = MONAD_EVENT_TXN_RECEIPT,
         .c_name = "TXN_RECEIPT",
         .description = "Transaction execution finished (merged into proposed block"},

    [MONAD_EVENT_WR_ACCT_STATE_BALANCE] =
        {.type = MONAD_EVENT_WR_ACCT_STATE_BALANCE,
         .c_name = "WR_ACCT_STATE_BALANCE",
         .description = "Account balance updated by transaction commit"},

    [MONAD_EVENT_WR_ACCT_STATE_STORAGE] =
        {.type = MONAD_EVENT_WR_ACCT_STATE_STORAGE,
         .c_name = "WR_ACCT_STATE_STORAGE",
         .description = "Account storage updated by transaction commit"},
};

size_t const g_monad_event_metadata_size = 17;

uint8_t const g_monad_event_metadata_hash[32] = {
    0x85, 0xda, 0x78, 0xa2, 0x79, 0xfb, 0xed, 0x17,
    0xe2, 0x46, 0xbc, 0x20, 0x76, 0xd6, 0xcd, 0x4a,
    0x62, 0xb2, 0x1d, 0x4b, 0x3c, 0x7d, 0xdd, 0xd1,
    0x7f, 0xcd, 0x0d, 0xab, 0x96, 0x20, 0xdf, 0x37,
};

#ifdef __cplusplus
} // extern "C"
#endif
