# Copyright (C) 2025-26 Category Labs, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Writes src/ecrecover_tables.rs: a*G + b*2^128*G on secp256k1 for
0 <= a, b < 64, (a, b) != (0, 0), at index a + 64*b - 1, affine, as the
little-endian 64-bit limbs ZisK's curve precompiles take. Run from zkvm/zisk:
python3 gen_ecrecover_tables.py > src/ecrecover_tables.rs"""

P = 2**256 - 2**32 - 977
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
G = (0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
     0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8)


def add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    if p[0] == q[0]:
        if (p[1] + q[1]) % P == 0:
            return None
        lam = 3 * p[0] * p[0] * pow(2 * p[1], P - 2, P) % P
    else:
        lam = (q[1] - p[1]) * pow(q[0] - p[0], P - 2, P) % P
    x = (lam * lam - p[0] - q[0]) % P
    return (x, (lam * (p[0] - x) - p[1]) % P)


def mul(k, p):
    r = None
    for bit in bin(k)[2:]:
        r = add(r, r) if r is not None else None
        if bit == "1":
            r = add(r, p)
    return r


def limbs(v):
    return ", ".join(f"0x{(v >> (64 * i)) & (2**64 - 1):016x}" for i in range(4))


assert mul(N, G) is None
G128 = mul(2**128, G)
A, B = [None], [None]
for _ in range(63):
    A.append(add(A[-1], G))
    B.append(add(B[-1], G128))
rows = []
for idx in range(1, 4096):
    x, y = add(A[idx % 64], B[idx // 64])
    assert (y * y - x * x * x - 7) % P == 0
    rows.append(f"    SyscallPoint256 {{ x: [{limbs(x)}], y: [{limbs(y)}] }},")
print("""// Copyright (C) 2025-26 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
""")
print("// Generated by gen_ecrecover_tables.py; do not edit.\n")
print("use ziskos::syscalls::SyscallPoint256;\n")
print("/// `G_JOINT[a + 64·b - 1]` is a·G + b·2^128·G, for a, b < 64.")
print("#[rustfmt::skip]")
print("pub(crate) static G_JOINT: [SyscallPoint256; 4095] = [")
print("\n".join(rows))
print("];")
