// Copyright (C) 2025-26 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

//! BLS12-381 map-to-curve, backing the EIP-2537 `MAP_FP_TO_G1` (0x10) and
//! `MAP_FP2_TO_G2` (0x11) precompiles.
//!
//! Both are RFC 9380's `map_to_curve` for the respective group, followed by
//! `clear_cofactor`: simplified SWU onto a curve isogenous to the real one,
//! the isogeny back, then multiplication by `h_eff`. There is no OpenVM
//! extension for any of this — only the underlying Fp and Fp2 operations are
//! accelerated.
//!
//! The isogeny coefficient tables are written big-endian so they can be read
//! straight against RFC 9380 sections 8.8.1 and 8.8.2. They were generated by
//! converting `third_party/blst/src/map_to_g{1,2}.c` out of Montgomery form
//! (blst stores `k << 384 mod p` as six little-endian 64-bit limbs), which is
//! also how they were checked: a Python transcription of this file reproduces
//! all 210 go-ethereum `blsMapG{1,2}.json` outputs.

use openvm_algebra_guest::{DivUnsafe, Field, IntMod, Sqrt};
use openvm_ecc_guest::weierstrass::WeierstrassPoint;
use openvm_pairing::bls12_381::{Fp, Fp2, G1Affine, G2Affine};

use crate::accel::{hex_nibble, mul_be_bytes};

// `Fp` implements both `IntMod` and `Field`, and both declare `ZERO`/`ONE`,
// so the unqualified names are ambiguous once this module imports the two
// traits. Name them once here instead of qualifying at every use.
const FP_ZERO: Fp = <Fp as IntMod>::ZERO;
const FP_ONE: Fp = <Fp as IntMod>::ONE;
const FP2_ZERO: Fp2 = <Fp2 as Field>::ZERO;
const FP2_ONE: Fp2 = <Fp2 as Field>::ONE;

/// `h_eff` for G1 (RFC 9380 section 8.8.1), big-endian: `1 - z`, where `z` is
/// the BLS12-381 seed `-0xd201000000010000`.
const G1_H_EFF: [u8; 8] = [0xd2, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01];

/// `h_eff` for G2 (RFC 9380 section 8.8.2), big-endian. Unlike G1's this is
/// not the bare group cofactor, so it cannot be recomputed from the seed —
/// the EIP-2537 vectors pin the exact multiplier.
const G2_H_EFF: [u8; 80] = [
    0x0b, 0xc6, 0x9f, 0x08, 0xf2, 0xee, 0x75, 0xb3, 0x58, 0x4c, 0x6a, 0x0e,
    0xa9, 0x1b, 0x35, 0x28, 0x88, 0xe2, 0xa8, 0xe9, 0x14, 0x5a, 0xd7, 0x68,
    0x99, 0x86, 0xff, 0x03, 0x15, 0x08, 0xff, 0xe1, 0x32, 0x9c, 0x2f, 0x17,
    0x87, 0x31, 0xdb, 0x95, 0x6d, 0x82, 0xbf, 0x01, 0x5d, 0x12, 0x12, 0xb0,
    0x2e, 0xc0, 0xec, 0x69, 0xd7, 0x47, 0x7c, 0x1a, 0xe9, 0x54, 0xcb, 0xc0,
    0x66, 0x89, 0xf6, 0xa3, 0x59, 0x89, 0x4c, 0x0a, 0xde, 0xbb, 0xf6, 0xb4,
    0xe8, 0x02, 0x00, 0x05, 0xaa, 0xa9, 0x55, 0x51,
];

/// A field element from a 96-character big-endian hex string. `IntMod` stores
/// its limbs little-endian, hence the reversal.
const fn fp(s: &str) -> Fp {
    let b = s.as_bytes();
    assert!(b.len() == 96);
    let mut le = [0u8; 48];
    let mut i = 0;
    while i < 48 {
        le[47 - i] = hex_nibble(b[2 * i]) * 16 + hex_nibble(b[2 * i + 1]);
        i += 1;
    }
    Fp::from_const_bytes(le)
}

const fn fp2(c0: &str, c1: &str) -> Fp2 {
    Fp2::new(fp(c0), fp(c1))
}

// -------------------------------------------------------------------------
// Field helpers
// -------------------------------------------------------------------------

/// RFC 9380 `sgn0` for Fp: the low bit of the canonical representative.
///
/// The reducedness assertion is not decoration. OpenVM's modular chips only
/// range-check their output limb-wise, so an intrinsic result is congruent
/// mod p but need not be the representative below p — and `p` is odd, so a
/// non-canonical encoding of an even value has the opposite low bit. Since
/// `sgn0` decides which of `y` and `-y` is returned, that would let a
/// dishonest prover flip the sign of the mapped point.
fn sgn0_fp(x: &Fp) -> bool {
    x.assert_reduced();
    x.as_le_bytes()[0] & 1 == 1
}

/// RFC 9380 `sgn0` for Fp2: `sgn0(c0)`, falling back to `sgn0(c1)` when `c0`
/// is zero.
fn sgn0_fp2(x: &Fp2) -> bool {
    sgn0_fp(&x.c0) || (x.c0 == FP_ZERO && sgn0_fp(&x.c1))
}

/// Square root in `Fp2 = Fp[i]/(i^2 + 1)` by the complex method, which is
/// valid because `p = 3 (mod 4)`.
///
/// `complex_declare!` generates no `Sqrt` impl — only `moduli_declare!` does,
/// via a host hint — so the extension field's square root has to be built
/// from the base field's. `None` means the input is not a square.
fn sqrt_fp2(a: &Fp2) -> Option<Fp2> {
    if a.c1 == FP_ZERO {
        // Purely real: either c0 is a square and the root is real, or -c0 is
        // and the root is purely imaginary (i^2 = -1).
        return match a.c0.sqrt() {
            Some(r) => Some(Fp2::new(r, FP_ZERO)),
            None => (-a.c0.clone()).sqrt().map(|r| Fp2::new(FP_ZERO, r)),
        };
    }
    // `a` is a square in Fp2 iff its norm c0^2 + c1^2 is a square in Fp.
    let norm = (&a.c0 * &a.c0 + &a.c1 * &a.c1).sqrt()?;
    let two = Fp::from_u8(2);
    // Exactly one of (c0 +- norm)/2 is a square; that one is the real part.
    let x0 = match (&a.c0 + &norm).div_unsafe(&two).sqrt() {
        Some(x0) => x0,
        None => (&a.c0 - &norm).div_unsafe(&two).sqrt()?,
    };
    // c1 != 0 here, so x0 != 0 and the division is defined.
    let x1 = a.c1.clone().div_unsafe(&x0 + &x0);
    Some(Fp2::new(x0, x1))
}

// -------------------------------------------------------------------------
// G1: Fp -> E1
// -------------------------------------------------------------------------

/// `Z` for the G1 SSWU map (RFC 9380 section 8.8.1).
fn swu_g1_z() -> Fp {
    Fp::from_u8(11)
}

/// The isogenous curve's equation `y^2 = x^3 + A' x + B'`, evaluated at `x`.
fn swu_g1_rhs(x: &Fp) -> Fp {
    x * x * x + &SWU_G1_A * x + SWU_G1_B
}

/// RFC 9380 appendix F.2, simplified SWU for `AB != 0`, onto the curve
/// 11-isogenous to BLS12-381 G1.
fn sswu_g1(u: &Fp) -> (Fp, Fp) {
    let zu2 = swu_g1_z() * (u * u);
    let d = &zu2 * &zu2 + &zu2;
    // x1 = (-B/A) * (1 + 1/d), degenerating to B/(Z*A) when d = 0. The branch
    // is required, not an optimisation: `div_unsafe` is undefined at zero,
    // whereas the RFC's `inv0` is defined to return zero there.
    let x1 = if d == FP_ZERO {
        SWU_G1_B.div_unsafe(swu_g1_z() * SWU_G1_A)
    } else {
        (-SWU_G1_B).div_unsafe(SWU_G1_A) * (FP_ONE + FP_ONE.div_unsafe(&d))
    };
    let (x, y) = match swu_g1_rhs(&x1).sqrt() {
        Some(y) => (x1, y),
        None => {
            let x2 = zu2 * &x1;
            // The map is constructed so that g(x2) is a square exactly when
            // g(x1) is not, so this cannot fail for any input.
            let y = swu_g1_rhs(&x2)
                .sqrt()
                .expect("SSWU: neither candidate x was on the curve");
            (x2, y)
        }
    };
    if sgn0_fp(u) == sgn0_fp(&y) {
        (x, y)
    } else {
        (x, -y)
    }
}

/// Horner evaluation of an isogeny coefficient table. `monic` tables omit
/// their leading 1.
fn horner_fp(coeffs: &[Fp], x: &Fp, monic: bool) -> Fp {
    let (mut acc, rest) = if monic {
        (FP_ONE, coeffs)
    } else {
        let (last, rest) = coeffs.split_last().expect("empty coefficient table");
        (last.clone(), rest)
    };
    for c in rest.iter().rev() {
        acc = acc * x + c;
    }
    acc
}

/// The 11-isogeny from the SSWU target curve back to BLS12-381 G1.
fn iso_map_g1(x: &Fp, y: &Fp) -> (Fp, Fp) {
    (
        horner_fp(&ISO_G1_X_NUM, x, false)
            .div_unsafe(horner_fp(&ISO_G1_X_DEN, x, true)),
        (horner_fp(&ISO_G1_Y_NUM, x, false) * y)
            .div_unsafe(horner_fp(&ISO_G1_Y_DEN, x, true)),
    )
}

/// EIP-2537 `MAP_FP_TO_G1`. `raw` is the 48-byte big-endian field element the
/// C++ shim has already stripped of its EVM zero padding. `None` means the
/// input was not a canonical field element.
pub fn map_fp_to_g1(raw: &[u8; 48]) -> Option<G1Affine> {
    let u = Fp::from_be_bytes(raw)?;
    let (x, y) = sswu_g1(&u);
    let (x, y) = iso_map_g1(&x, &y);
    // The isogeny lands on BLS12-381 itself, and `from_xy` re-checks the curve
    // equation rather than trusting the tables above — cheap next to the
    // cofactor multiplication that follows. Subgroup membership is what
    // `clear_cofactor` then establishes.
    let point = G1Affine::from_xy(x, y)?;
    Some(mul_be_bytes(&point, &G1_H_EFF))
}

// -------------------------------------------------------------------------
// G2: Fp2 -> E2
// -------------------------------------------------------------------------

// `A'`, `B'` and `Z` for the G2 SSWU map (RFC 9380 section 8.8.2): the
// isogenous curve is `y^2 = x^3 + 240i x + (1012 + 1012i)` and `Z = -(2 + i)`.
// Built from small integers rather than written out as field constants, since
// `-(2 + i)` would otherwise mean transcribing `p - 2` and `p - 1` by hand.

fn swu_g2_a() -> Fp2 {
    Fp2::new(FP_ZERO, Fp::from_u32(240))
}

fn swu_g2_b() -> Fp2 {
    Fp2::new(Fp::from_u32(1012), Fp::from_u32(1012))
}

fn swu_g2_z() -> Fp2 {
    -Fp2::new(Fp::from_u8(2), FP_ONE)
}

fn swu_g2_rhs(x: &Fp2) -> Fp2 {
    &(&(x * x) * x) + &(&swu_g2_a() * x + swu_g2_b())
}

/// RFC 9380 appendix F.2 over Fp2, onto the curve 3-isogenous to BLS12-381 G2.
/// Step for step the same map as `sswu_g1`, including why the `d == 0` case is
/// a separate branch rather than an `inv0`.
fn sswu_g2(u: &Fp2) -> (Fp2, Fp2) {
    let zu2 = &swu_g2_z() * &(u * u);
    let d = &(&zu2 * &zu2) + &zu2;
    let x1 = if d == FP2_ZERO {
        swu_g2_b().div_unsafe(&(&swu_g2_z() * &swu_g2_a()))
    } else {
        &(-swu_g2_b()).div_unsafe(&swu_g2_a())
            * &(&FP2_ONE + &FP2_ONE.div_unsafe(&d))
    };
    let (x, y) = match sqrt_fp2(&swu_g2_rhs(&x1)) {
        Some(y) => (x1, y),
        None => {
            let x2 = &zu2 * &x1;
            let y = sqrt_fp2(&swu_g2_rhs(&x2))
                .expect("SSWU: neither candidate x was on the curve");
            (x2, y)
        }
    };
    if sgn0_fp2(u) == sgn0_fp2(&y) {
        (x, y)
    } else {
        (x, -y)
    }
}

fn horner_fp2(coeffs: &[Fp2], x: &Fp2, monic: bool) -> Fp2 {
    let (mut acc, rest) = if monic {
        (FP2_ONE, coeffs)
    } else {
        let (last, rest) = coeffs.split_last().expect("empty coefficient table");
        (last.clone(), rest)
    };
    for c in rest.iter().rev() {
        acc = &(&acc * x) + c;
    }
    acc
}

/// The 3-isogeny from the SSWU target curve back to BLS12-381 G2.
fn iso_map_g2(x: &Fp2, y: &Fp2) -> (Fp2, Fp2) {
    (
        horner_fp2(&ISO_G2_X_NUM, x, false)
            .div_unsafe(&horner_fp2(&ISO_G2_X_DEN, x, true)),
        (&horner_fp2(&ISO_G2_Y_NUM, x, false) * y)
            .div_unsafe(&horner_fp2(&ISO_G2_Y_DEN, x, true)),
    )
}

/// EIP-2537 `MAP_FP2_TO_G2`. `raw` is `c0 || c1`, 48-byte big-endian each.
pub fn map_fp2_to_g2(raw: &[u8; 96]) -> Option<G2Affine> {
    let u = Fp2::new(
        Fp::from_be_bytes(&raw[..48])?,
        Fp::from_be_bytes(&raw[48..])?,
    );
    let (x, y) = sswu_g2(&u);
    let (x, y) = iso_map_g2(&x, &y);
    // As map_fp_to_g1.
    let point = G2Affine::from_xy(x, y)?;
    Some(mul_be_bytes(&point, &G2_H_EFF))
}

// -------------------------------------------------------------------------
// Isogeny coefficients (RFC 9380 sections 8.8.1 and 8.8.2)
// -------------------------------------------------------------------------

/// k_(1,i), i = 0..=11: numerator of the isogeny's x map.
const ISO_G1_X_NUM: [Fp; 12] = [
    fp("11a05f2b1e833340b809101dd99815856b303e88a2d7005ff2627b56cdb4e2c85610c2d5f2e62d6eaeac1662734649b7"),
    fp("17294ed3e943ab2f0588bab22147a81c7c17e75b2f6a8417f565e33c70d1e86b4838f2a6f318c356e834eef1b3cb83bb"),
    fp("0d54005db97678ec1d1048c5d10a9a1bce032473295983e56878e501ec68e25c958c3e3d2a09729fe0179f9dac9edcb0"),
    fp("1778e7166fcc6db74e0609d307e55412d7f5e4656a8dbf25f1b33289f1b330835336e25ce3107193c5b388641d9b6861"),
    fp("0e99726a3199f4436642b4b3e4118e5499db995a1257fb3f086eeb65982fac18985a286f301e77c451154ce9ac8895d9"),
    fp("1630c3250d7313ff01d1201bf7a74ab5db3cb17dd952799b9ed3ab9097e68f90a0870d2dcae73d19cd13c1c66f652983"),
    fp("0d6ed6553fe44d296a3726c38ae652bfb11586264f0f8ce19008e218f9c86b2a8da25128c1052ecaddd7f225a139ed84"),
    fp("17b81e7701abdbe2e8743884d1117e53356de5ab275b4db1a682c62ef0f2753339b7c8f8c8f475af9ccb5618e3f0c88e"),
    fp("080d3cf1f9a78fc47b90b33563be990dc43b756ce79f5574a2c596c928c5d1de4fa295f296b74e956d71986a8497e317"),
    fp("169b1f8e1bcfa7c42e0c37515d138f22dd2ecb803a0c5c99676314baf4bb1b7fa3190b2edc0327797f241067be390c9e"),
    fp("10321da079ce07e272d8ec09d2565b0dfa7dccdde6787f96d50af36003b14866f69b771f8c285decca67df3f1605fb7b"),
    fp("06e08c248e260e70bd1e962381edee3d31d79d7e22c837bc23c0bf1bc24c6b68c24b1b80b64d391fa9c8ba2e8ba2d229"),
];

/// k_(2,i), i = 0..=9: denominator of the x map. Monic of degree 10, so the leading 1 is implicit.
const ISO_G1_X_DEN: [Fp; 10] = [
    fp("08ca8d548cff19ae18b2e62f4bd3fa6f01d5ef4ba35b48ba9c9588617fc8ac62b558d681be343df8993cf9fa40d21b1c"),
    fp("12561a5deb559c4348b4711298e536367041e8ca0cf0800c0126c2588c48bf5713daa8846cb026e9e5c8276ec82b3bff"),
    fp("0b2962fe57a3225e8137e629bff2991f6f89416f5a718cd1fca64e00b11aceacd6a3d0967c94fedcfcc239ba5cb83e19"),
    fp("03425581a58ae2fec83aafef7c40eb545b08243f16b1655154cca8abc28d6fd04976d5243eecf5c4130de8938dc62cd8"),
    fp("13a8e162022914a80a6f1d5f43e7a07dffdfc759a12062bb8d6b44e833b306da9bd29ba81f35781d539d395b3532a21e"),
    fp("0e7355f8e4e667b955390f7f0506c6e9395735e9ce9cad4d0a43bcef24b8982f7400d24bc4228f11c02df9a29f6304a5"),
    fp("0772caacf16936190f3e0c63e0596721570f5799af53a1894e2e073062aede9cea73b3538f0de06cec2574496ee84a3a"),
    fp("14a7ac2a9d64a8b230b3f5b074cf01996e7f63c21bca68a81996e1cdf9822c580fa5b9489d11e2d311f7d99bbdcc5a5e"),
    fp("0a10ecf6ada54f825e920b3dafc7a3cce07f8d1d7161366b74100da67f39883503826692abba43704776ec3a79a1d641"),
    fp("095fc13ab9e92ad4476d6e3eb3a56680f682b4ee96f7d03776df533978f31c1593174e4b4b7865002d6384d168ecdd0a"),
];

/// k_(3,i), i = 0..=15: numerator of the isogeny's y map.
const ISO_G1_Y_NUM: [Fp; 16] = [
    fp("090d97c81ba24ee0259d1f094980dcfa11ad138e48a869522b52af6c956543d3cd0c7aee9b3ba3c2be9845719707bb33"),
    fp("134996a104ee5811d51036d776fb46831223e96c254f383d0f906343eb67ad34d6c56711962fa8bfe097e75a2e41c696"),
    fp("00cc786baa966e66f4a384c86a3b49942552e2d658a31ce2c344be4b91400da7d26d521628b00523b8dfe240c72de1f6"),
    fp("01f86376e8981c217898751ad8746757d42aa7b90eeb791c09e4a3ec03251cf9de405aba9ec61deca6355c77b0e5f4cb"),
    fp("08cc03fdefe0ff135caf4fe2a21529c4195536fbe3ce50b879833fd221351adc2ee7f8dc099040a841b6daecf2e8fedb"),
    fp("16603fca40634b6a2211e11db8f0a6a074a7d0d4afadb7bd76505c3d3ad5544e203f6326c95a807299b23ab13633a5f0"),
    fp("04ab0b9bcfac1bbcb2c977d027796b3ce75bb8ca2be184cb5231413c4d634f3747a87ac2460f415ec961f8855fe9d6f2"),
    fp("0987c8d5333ab86fde9926bd2ca6c674170a05bfe3bdd81ffd038da6c26c842642f64550fedfe935a15e4ca31870fb29"),
    fp("09fc4018bd96684be88c9e221e4da1bb8f3abd16679dc26c1e8b6e6a1f20cabe69d65201c78607a360370e577bdba587"),
    fp("0e1bba7a1186bdb5223abde7ada14a23c42a0ca7915af6fe06985e7ed1e4d43b9b3f7055dd4eba6f2bafaaebca731c30"),
    fp("19713e47937cd1be0dfd0b8f1d43fb93cd2fcbcb6caf493fd1183e416389e61031bf3a5cce3fbafce813711ad011c132"),
    fp("18b46a908f36f6deb918c143fed2edcc523559b8aaf0c2462e6bfe7f911f643249d9cdf41b44d606ce07c8a4d0074d8e"),
    fp("0b182cac101b9399d155096004f53f447aa7b12a3426b08ec02710e807b4633f06c851c1919211f20d4c04f00b971ef8"),
    fp("0245a394ad1eca9b72fc00ae7be315dc757b3b080d4c158013e6632d3c40659cc6cf90ad1c232a6442d9d3f5db980133"),
    fp("05c129645e44cf1102a159f748c4a3fc5e673d81d7e86568d9ab0f5d396a7ce46ba1049b6579afb7866b1e715475224b"),
    fp("15e6be4e990f03ce4ea50b3b42df2eb5cb181d8f84965a3957add4fa95af01b2b665027efec01c7704b456be69c8b604"),
];

/// k_(4,i), i = 0..=14: denominator of the y map. Monic of degree 15, so the leading 1 is implicit.
const ISO_G1_Y_DEN: [Fp; 15] = [
    fp("16112c4c3a9c98b252181140fad0eae9601a6de578980be6eec3232b5be72e7a07f3688ef60c206d01479253b03663c1"),
    fp("1962d75c2381201e1a0cbd6c43c348b885c84ff731c4d59ca4a10356f453e01f78a4260763529e3532f6102c2e49a03d"),
    fp("058df3306640da276faaae7d6e8eb15778c4855551ae7f310c35a5dd279cd2eca6757cd636f96f891e2538b53dbf67f2"),
    fp("16b7d288798e5395f20d23bf89edb4d1d115c5dbddbcd30e123da489e726af41727364f2c28297ada8d26d98445f5416"),
    fp("0be0e079545f43e4b00cc912f8228ddcc6d19c9f0f69bbb0542eda0fc9dec916a20b15dc0fd2ededda39142311a5001d"),
    fp("08d9e5297186db2d9fb266eaac783182b70152c65550d881c5ecd87b6f0f5a6449f38db9dfa9cce202c6477faaf9b7ac"),
    fp("166007c08a99db2fc3ba8734ace9824b5eecfdfa8d0cf8ef5dd365bc400a0051d5fa9c01a58b1fb93d1a1399126a775c"),
    fp("16a3ef08be3ea7ea03bcddfabba6ff6ee5a4375efa1f4fd7feb34fd206357132b920f5b00801dee460ee415a15812ed9"),
    fp("1866c8ed336c61231a1be54fd1d74cc4f9fb0ce4c6af5920abc5750c4bf39b4852cfe2f7bb9248836b233d9d55535d4a"),
    fp("167a55cda70a6e1cea820597d94a84903216f763e13d87bb5308592e7ea7d4fbc7385ea3d529b35e346ef48bb8913f55"),
    fp("04d2f259eea405bd48f010a01ad2911d9c6dd039bb61a6290e591b36e636a5c871a5c29f4f83060400f8b49cba8f6aa8"),
    fp("0accbb67481d033ff5852c1e48c50c477f94ff8aefce42d28c0f9a88cea7913516f968986f7ebbea9684b529e2561092"),
    fp("0ad6b9514c767fe3c3613144b45f1496543346d98adf02267d5ceef9a00d9b8693000763e3b90ac11e99b138573345cc"),
    fp("02660400eb2e4f3b628bdd0d53cd76f2bf565b94e72927c1cb748df27942480e420517bd8714cc80d1fadc1326ed06f7"),
    fp("0e0fa1d816ddc03e6b24255e0d7819c171c40f65e273b853324efcd6356caa205ca2f570f13497804415473a1d634b8f"),
];

/// k_(1,i), i = 0..=3: numerator of the isogeny's x map.
const ISO_G2_X_NUM: [Fp2; 4] = [
    fp2(
        "05c759507e8e333ebb5b7a9a47d7ed8532c52d39fd3a042a88b58423c50ae15d5c2638e343d9c71c6238aaaaaaaa97d6",
        "05c759507e8e333ebb5b7a9a47d7ed8532c52d39fd3a042a88b58423c50ae15d5c2638e343d9c71c6238aaaaaaaa97d6",
    ),
    fp2(
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "11560bf17baa99bc32126fced787c88f984f87adf7ae0c7f9a208c6b4f20a4181472aaa9cb8d555526a9ffffffffc71a",
    ),
    fp2(
        "11560bf17baa99bc32126fced787c88f984f87adf7ae0c7f9a208c6b4f20a4181472aaa9cb8d555526a9ffffffffc71e",
        "08ab05f8bdd54cde190937e76bc3e447cc27c3d6fbd7063fcd104635a790520c0a395554e5c6aaaa9354ffffffffe38d",
    ),
    fp2(
        "171d6541fa38ccfaed6dea691f5fb614cb14b4e7f4e810aa22d6108f142b85757098e38d0f671c7188e2aaaaaaaa5ed1",
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    ),
];

/// k_(2,i), i = 0..=1: denominator of the x map. Monic of degree 2, so the leading 1 is implicit.
const ISO_G2_X_DEN: [Fp2; 2] = [
    fp2(
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaa63",
    ),
    fp2(
        "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c",
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaa9f",
    ),
];

/// k_(3,i), i = 0..=3: numerator of the isogeny's y map.
const ISO_G2_Y_NUM: [Fp2; 4] = [
    fp2(
        "1530477c7ab4113b59a4c18b076d11930f7da5d4a07f649bf54439d87d27e500fc8c25ebf8c92f6812cfc71c71c6d706",
        "1530477c7ab4113b59a4c18b076d11930f7da5d4a07f649bf54439d87d27e500fc8c25ebf8c92f6812cfc71c71c6d706",
    ),
    fp2(
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "05c759507e8e333ebb5b7a9a47d7ed8532c52d39fd3a042a88b58423c50ae15d5c2638e343d9c71c6238aaaaaaaa97be",
    ),
    fp2(
        "11560bf17baa99bc32126fced787c88f984f87adf7ae0c7f9a208c6b4f20a4181472aaa9cb8d555526a9ffffffffc71c",
        "08ab05f8bdd54cde190937e76bc3e447cc27c3d6fbd7063fcd104635a790520c0a395554e5c6aaaa9354ffffffffe38f",
    ),
    fp2(
        "124c9ad43b6cf79bfbf7043de3811ad0761b0f37a1e26286b0e977c69aa274524e79097a56dc4bd9e1b371c71c718b10",
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    ),
];

/// k_(4,i), i = 0..=2: denominator of the y map. Monic of degree 3, so the leading 1 is implicit.
const ISO_G2_Y_DEN: [Fp2; 3] = [
    fp2(
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffa8fb",
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffa8fb",
    ),
    fp2(
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffa9d3",
    ),
    fp2(
        "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012",
        "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaa99",
    ),
];

const SWU_G1_A: Fp = fp("00144698a3b8e9433d693a02c96d4982b0ea985383ee66a8d8e8981aefd881ac98936f8da0e0f97f5cf428082d584c1d");
const SWU_G1_B: Fp = fp("12e2908d11688030018b12e8753eee3b2016c1f0f24f4070a0b9c14fcef35ef55a23215a316ceaa5d1cc48e98e172be0");
