name: Code Quality Checks

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || (github.event_name == 'push' && github.ref) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  formatting-check:
    name: Check clang-format
    runs-on: ubuntu-26.04
    env:
      LLVM_VERSION: '19'

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format-${{ env.LLVM_VERSION }}
        run: |
          sudo apt install -y clang-format-${{ env.LLVM_VERSION }}

      - name: Run clang-format check
        run: |
          find category cmd test -regex '.*\.\(cpp\|hpp\|c\|h\)' -exec clang-format-${{ env.LLVM_VERSION }} -style=file --dry-run --Werror {} +

  traits-check:
    name: Trait instantiation check
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Check instantiations
        run: uv run scripts/check-trait-instantiations.py category

  clang-tidy:
    name: Check clang-tidy
    runs-on: ubuntu-26.04-32

    steps:
      - uses: actions/checkout@v4

      - name: Build `code_quality` stage
        uses: ./.github/actions/docker-stage
        with:
          target: code_quality
          setup: true
          submodules: true
          cache-from: |
            type=gha,scope=base_vm_test
            type=gha,scope=base
