name: Cache RISC-V Toolchain

on:
  push:
    branches: ["main"]
    paths:
      - '.github/actions/docker-stage/**'
      - 'docker/Dockerfile'
      - 'nix/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cache-riscv:
    runs-on: ubuntu-26.04-32

    steps:
      - uses: actions/checkout@v4

      - name: Build and cache `base_riscv_toolchain` stage
        uses: ./.github/actions/docker-stage
        with:
          target: base_riscv_toolchain
          setup: true
          cache-from: |
            type=gha,scope=riscv-toolchain
            type=gha,scope=base
          cache-to: type=gha,mode=max,scope=riscv-toolchain
