name: Docker

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || (github.event_name == 'push' && github.ref) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    strategy:
      matrix:
        CMAKE_BUILD_TYPE: [RelWithDebInfo, Debug]
        compiler: [{CXX: g++-15, CC: gcc-15}, {CXX: clang++-19, CC: clang-19}]

    runs-on: ubuntu-26.04-32

    steps:
      - uses: actions/checkout@v4

      - name: Reserve hugepages
        run: |
          hugepages=/sys/devices/system/node/node0/hugepages
          echo 2048 | sudo tee $hugepages/hugepages-2048kB/nr_hugepages
          echo 8 | sudo tee $hugepages/hugepages-1048576kB/nr_hugepages
          cat $hugepages/hugepages-*/nr_hugepages

      - name: Build `build_and_test` stage
        uses: ./.github/actions/docker-stage
        with:
          target: build_and_test
          setup: true
          submodules: true
          build-args: |
            CC=${{ matrix.compiler.CC }}
            CXX=${{ matrix.compiler.CXX }}
            CMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }}
            TOOLCHAIN=gcc-avx2
          allow: security.insecure # for tests which use io_uring
          cache-from: type=gha,scope=base
