name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || (github.event_name == 'push' && github.ref) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-26.04-32

    steps:
      - uses: actions/checkout@v4

      - name: Build `build_and_test_rust` stage
        uses: ./.github/actions/docker-stage
        with:
          target: build_and_test_rust
          setup: true
          submodules: true
          build-args: |
            CC=gcc-15
            CXX=g++-15
          cache-from: type=gha,scope=base_rust

      - name: Build `code_quality_rust` stage
        uses: ./.github/actions/docker-stage
        with:
          target: code_quality_rust
          cache-from: type=gha,scope=base_rust
