name: VM Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '.github/workflows/test-vm.yml'
      - '.github/actions/docker-stage/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'category/vm/**'
      - 'cmd/vm/**'
      - 'scripts/vm/**'
      - 'test/vm/**'
      - 'docker/Dockerfile'
      - 'scripts/ubuntu-build/install-ocaml.sh'
      - 'third_party/monad-execution-specs'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || (github.event_name == 'push' && github.ref) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Test compiler
    runs-on: ubuntu-26.04-32
    strategy:
      matrix:
        build:
          - CMAKE_BUILD_TYPE: RelWithDebInfo
            TOOLCHAIN: gcc-avx2
          - CMAKE_BUILD_TYPE: Debug
            TOOLCHAIN: gcc-asan
        compiler:
          - CXX: g++-15
            CC: gcc-15
          - CXX: clang++-19
            CC: clang-19
        exclude:
          # GCC's implementation of ASAN breaks the must-tail calling
          # convention used by the interpreter, so we need to disable that
          # configuration when running with sanitizers enabled.
          - build:
              CMAKE_BUILD_TYPE: Debug
              TOOLCHAIN: gcc-asan
            compiler:
              CXX: g++-15
              CC: gcc-15

    steps:
      - uses: actions/checkout@v4

      - name: Build `build_and_test_vm` stage
        uses: ./.github/actions/docker-stage
        with:
          target: build_and_test_vm
          setup: true
          submodules: true
          build-args: |
            CC=${{ matrix.compiler.CC }}
            CXX=${{ matrix.compiler.CXX }}
            CMAKE_BUILD_TYPE=${{ matrix.build.CMAKE_BUILD_TYPE }}
            TOOLCHAIN=${{ matrix.build.TOOLCHAIN }}
          cache-from: |
            type=gha,scope=base_vm_test
            type=gha,scope=base

  fuzz:
    name: VM Fuzz Tests
    runs-on: ubuntu-26.04-32

    steps:
      - uses: actions/checkout@v4

      - name: Build `vm_fuzz` stage
        uses: ./.github/actions/docker-stage
        with:
          target: vm_fuzz
          setup: true
          submodules: true
          cache-from: |
            type=gha,scope=base_vm_test
            type=gha,scope=base

  python-code-quality:
    name: Python code quality checks
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: scripts/vm/benchmark-analysis/.python-version

      - name: Check Python code
        working-directory: scripts/vm/benchmark-analysis
        run: make check
